version: "2.4"

networks:
  military:
    name: military_net

services:
  server1_1:
    image: openjdk:8
    labels:
      service: peer0_org1
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
    # volumes:
    #   - /root/fabric/military/server/org1:/var/server/org1
    ports:
      - 880:888
      - 881:889
    container_name: server1_1
    command: nohup java -jar /var/server/org1/server-0.0.1-SNAPSHOT.jar >>./log.log 2>&1 &
    networks:
      - military
